version: '3.8'
services:
  design_product:
    container_name: design_product
    image: design_product
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/designproduct
    ports:
      - "3002:3002"
    environment:
      DATABASE_USERNAME: shivani
      DATABASE_PASSWORD: test123
      DATABASE_HOST: product_design_db
      RAILS_ENV: development
    depends_on:
      - db
  
  db:
    container_name: product_design_db
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: shivani
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: design_product_development
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
