version: '3.8'
services:
  design_product:
    container_name: design_product
    image: design_product
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/designproduct
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db:
    container_name: product_design_db
    image: postgres:15
    ports:
      - "3306:3306"
    restart: always
    environment:
      POSTGRES_USER: design_product
      POSTGRES_PASSWORD: <%= ENV["DESIGN_PRODUCT_DATABASE_PASSWORD"] %>
      POSTGRES_DB: design_product_development
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:



# C:\Program Files\PostgreSQL\14
# C:\Program Files\PostgreSQL\14\data